<?php if(Session::isConnected() && $_SESSION['auth']['role']) : ?>
    <h2>Ajouter un article</h2>
        <form method="post" action="add_post.php">
            <fieldset>
                <legend>Nouvel article</legend>
                <label for="title">Titre
                    <input type="text" name="title" id="title" value=""/>
                </label>

            </fieldset>
            <fieldset>
                <legend>Contenu</legend>
                <label for="content">Message
                    <textarea name="content" id="content" class="textarea-field" required></textarea>
                </label>    
                
                    <label><input type="submit" value="Envoyer"></label>
                
                <label>
                    <a href="dashboard.php">Annuler</a>
                </label>
            </fieldset>
        </form>
<?php endif; ?>        