

<form action="contact.php" method="post">
    <h2>Envoyez nous un message</h2>

        <label for="name">Nom / Prénom</label>
        <input id="name" type="text" name="name" placeholder="Votre nom" required>

        <label for="name">Votre adresse e-mail</label>
        <input id="mail" type="text" name="mail" placeholder="Votre adresse email" required>

        <label for="name">Votre numéro de téléphone</label>
        <input id="phone" type="text" name="phone" placeholder="Votre numéro de téléphone" required>

        <label for="name">Le sujet de votre message</label>
        <input id="subject" type="text" name="subject" placeholder="Votre demande" required>
        
        <label for="name">Veuillez saisir votre message</label>
        <textarea id="content" name="content" placeholder="Votre message" required></textarea>

        <input type="submit" data-submit="...en cours d'envoi" value="Envoyer">

</form>