<div class="banner_image">
    
        <img class="banner_img_dog" src="./public/assets/images/dobermann_test.jpg" alt="" >
        <div class="banner_content">
            <h1>Nos Amis Les Animaux</h1>
                <h2>Aucune raison ne justifie l'abandon</h2>
                    <p>Découvrez le film de sensibilisation de la Société Protectrice des Animaux <a href="https://lp.la-spa.fr/stopabandon/?reserved_code_media=W22PG012F&utm_medium=mainbloc&utm_campaign=Abandon22&utm_source=site">juste ici</a></p>
        </div>
</div>






<h2>Nous avons <?= $countAnimals ?> animaux à l'adoption !</h2>

<div class="animals-fiche">
<table>
    <?php foreach ($animals as $animal) : ?>
        <thead>
            <tr class="title-animals">
                <th>Nom</th>
                <th>Sexe</th>
                <th>Refuge</th>
                <th>Date de Naissance</th>
                <th></th>
            </tr>
        </thead>
            <tbody>
                <tr class="content-animals">
                    <td class="test1">
                        <?= htmlspecialchars($animal['name']); ?>
                    </td>
                    <td>
                        <?= htmlspecialchars($animal['sex']); ?>
                    </td>
                    <td>
                        <?= htmlspecialchars($animal['refuge']); ?>
                    </td>
                    <td>
                        <?= htmlspecialchars($animal['date_of_birth']); ?>
                    </td>
                    <td>
                        <img class="animals-img" src="<?= strtok($animal["files"], ',') ?>" alt="images" />
                    </td>
                </tr>
    <?php endforeach ?>
        </tbody>
</table>
</div>



            
            
            
            

            
        
    
    
</div>