<div class="form_center">
    <form action="register.php" method="post">
        <h2>Créer un compte</h2>
            <fieldset>
                <label for="firstname">Prénom</label>
                <input type="text" name="firstname" placeholder="Votre prénom" id="firstname" required/>
            

                <label for="lastname">Nom</label>
                <input type="text" name="lastname" placeholder="Votre nom" id="lastname" required/>
            

        
                <label for="mail">E-mail</label>
                <input type="text" name="mail" placeholder="Votre adresse email" id="mail" required/>
            

            
                <label for="phone">Téléphone</label>
                <input type="text" name="phone" placeholder="Votre numéro de téléphone" id="phone" required/>
            

            
                <label for="address">Adresse</label>
                <input type="text" name="address" placeholder="Votre adresse" id="address" required/>
            

            
                <label for="city">Ville</label>
                <input type="text" name="city" placeholder="Votre ville" id="city" required/>
            

            
                <label for="zipcode">Code postal</label>
                <input type="text" name="zipcode" placeholder="Votre code postal" id="zipcode" required/>
            

            
                <label for="password">Mot de passe</label>
                <input type="password" name="password" placeholder="Votre mot de passe" id="password" required/>
            

            
                <input type="submit" value="S'enregistrer"/>
                <label>
                            <a href="index.php">Annuler</a>
                </label>
            </fieldset>

    </form>
</div>